add copy of designsystem repo

diff --git a/.github/workflows/docs-and-package.yaml b/.github/workflows/docs-and-package.yaml
--- a/.github/workflows/docs-and-package.yaml
+++ b/.github/workflows/docs-and-package.yaml
@@ -5,14 +5,15 @@ permissions:
   id-token: write
 
 on:
-  push:
+  workflow_dispatch:
+  pull_request:
     branches:
       - master
 
 jobs:
   run:
     runs-on: ubuntu-latest
-    environment: development
+    environment: production
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -25,25 +26,39 @@ jobs:
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
+      - name: Guard - BREAKING CHANGE should not be in body
+        id: guard_breaking_change
+        run: |
+          LAST_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
+          echo "Commit message: \"$LAST_COMMIT_MESSAGE\""
+          if [[ "$LAST_COMMIT_MESSAGE" == *"BREAKING CHANGE"* ]]; then
+              echo "ERROR: Commit message should not include 'BREAKING CHANGE'."
+              exit 1
+          fi
+        shell: bash
 
-      - name: Guard - prefix
-        id: prefix
+      - name: Guard - Decide if Package & Docs should run
+        id: guard_job
         run: |
           LAST_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
           echo "Commit message: \"$LAST_COMMIT_MESSAGE\""
           if [[ "$LAST_COMMIT_MESSAGE" != feat:\ * && "$LAST_COMMIT_MESSAGE" != fix:\ * ]]; then
               echo "Commit message does not include 'feat: ' nor 'fix: '. Package & Docs pipeline will not run."
-              exit 1
+              echo "should_run=false" >> "$GITHUB_OUTPUT"
+          else
+              echo "should_run=true" >> "$GITHUB_OUTPUT"
           fi
         shell: bash
 
       - name: Install pnpm
+        if: steps.guard_job.outputs.should_run == 'true'
         uses: pnpm/action-setup@v4
         with:
           version: 9
           run_install: false
 
       - name: Install Node.js
+        if: steps.guard_job.outputs.should_run == 'true'
         uses: actions/setup-node@v4
         with:
           node-version: lts/*
@@ -52,27 +67,39 @@ jobs:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
 
       - name: Install dependencies
+        if: steps.guard_job.outputs.should_run == 'true'
         run: pnpm i
 
       - name: Lint
+        if: steps.guard_job.outputs.should_run == 'true'
         run: cd packages/fhi-designsystem; pnpm lint
 
       - name: Build
+        if: steps.guard_job.outputs.should_run == 'true'
         run: cd packages/fhi-designsystem; pnpm build
 
       - name: Prepare Testing Environment
-        run: cd packages/fhi-designsystem; pnpm exec playwright install --with-deps chromium webkit
+        if: steps.guard_job.outputs.should_run == 'true'
+        run: cd packages/fhi-designsystem; pnpm exec playwright install --with-deps
 
       - name: Test
+        if: steps.guard_job.outputs.should_run == 'true'
         run: cd packages/fhi-designsystem; pnpm test
 
       - name: Ping NPM registry
+        if: steps.guard_job.outputs.should_run == 'true'
         run: npm ping
 
-      - name: Update Changelog
+      - name: Update Changelog and Bump Version
+        if: steps.guard_job.outputs.should_run == 'true'
         run: cd packages/fhi-designsystem; pnpm changelog:ci
         env:
           GITHUB_TOKEN: ${{secrets.REPO_GITHUB_TOKEN}}
 
+      - name: Include Updates In Build
+        if: steps.guard_job.outputs.should_run == 'true'
+        run: cd packages/fhi-designsystem; pnpm build
+
       - name: Publish package to NPM
+        if: steps.guard_job.outputs.should_run == 'true'
         run: cd packages/fhi-designsystem/dist/npm; npm publish --provenance --access public
