catch errro

diff --git a/.github/workflows/github-package.yaml b/.github/workflows/github-package.yaml
--- a/.github/workflows/github-package.yaml
+++ b/.github/workflows/github-package.yaml
@@ -10,34 +10,34 @@ on:
     types: [opened, synchronize, reopened, closed]
     branches: [master]
 
-env: 
-  PACKAGE_SCOPE: "@dafn-dummy-repo"
-  PACKAGE_NAME: "pull-request-${{ github.event.pull_request.number }}"
-  PACKAGE_VERSION: "0.0.${{ github.run_number }}"
+env:
+  PACKAGE_SCOPE: '@dafn-dummy-repo'
+  PACKAGE_NAME: 'pull-request-${{ github.event.pull_request.number }}'
+  PACKAGE_VERSION: '0.0.${{ github.run_number }}'
 
 jobs:
   check_for_changes:
     runs-on: ubuntu-latest
     if: github.event.action != 'closed'
     outputs:
-        should_publish_package: ${{ steps.check_files.outputs.should_publish_package }}
+      should_publish_package: ${{ steps.check_files.outputs.should_publish_package }}
     steps:
-        - name: Checkout
-          uses: actions/checkout@v4
-          with:
-            fetch-depth: 0
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-        - name: Check if component or styling files changed
-          id: check_files
-          run: |
-            changed=$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep -E '\.(component\.ts|css)$' || true)
-            if [ -n "$changed" ]; then
-              echo "Found changed component or css files. Proceeding..."
-              echo "should_publish_package=true" >> $GITHUB_OUTPUT
-            else
-              echo "No component or css files changed. Skipping workflow."
-              echo "should_publish_package=false" >> $GITHUB_OUTPUT
-            fi
+      - name: Check if component or styling files changed
+        id: check_files
+        run: |
+          changed=$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep -E '\.(component\.ts|css)$' || true)
+          if [ -n "$changed" ]; then
+            echo "Found changed component or css files. Proceeding..."
+            echo "should_publish_package=true" >> $GITHUB_OUTPUT
+          else
+            echo "No component or css files changed. Skipping workflow."
+            echo "should_publish_package=false" >> $GITHUB_OUTPUT
+          fi
 
   publish_github_package:
     needs: check_for_changes
@@ -94,11 +94,15 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            await github.rest.packages.deletePackageForOrg({
-              package_type: "npm",
-              package_name: `${{ env.PACKAGE_SCOPE }}/${{ env.PACKAGE_NAME }}`,
-              org: "FHIDev"
-            })
+            try {
+              await github.rest.packages.deletePackageForOrg({
+                package_type: "npm",
+                package_name: `${{ env.PACKAGE_SCOPE }}/${{ env.PACKAGE_NAME }}`,
+                org: "FHIDev"
+              })
+            } catch (error) {
+              console.warn("No existing package to delete or error occurred:", error.status);
+            }
 
       - name: Configure npm for GitHub Packages
         working-directory: ./packages/fhi-designsystem/dist/github
@@ -132,17 +136,17 @@ jobs:
                   })
 
   clean_up_github_package:
-      if: github.event.action == 'closed'
-      runs-on: ubuntu-latest
-      environment: development
-      steps:
-        - name: Clean up potential PR staging package
-          uses: actions/github-script@v8
-          with:
-            github-token: ${{ secrets.GITHUB_TOKEN }}
-            script: |
-              await github.rest.packages.deletePackageForOrg({
-                package_type: "npm",
-                package_name: `${{ env.PACKAGE_SCOPE }}/${{ env.PACKAGE_NAME }}`,
-                org: "FHIDev"
-              })
+    if: github.event.action == 'closed'
+    runs-on: ubuntu-latest
+    environment: development
+    steps:
+      - name: Clean up potential PR staging package
+        uses: actions/github-script@v8
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            await github.rest.packages.deletePackageForOrg({
+              package_type: "npm",
+              package_name: `${{ env.PACKAGE_SCOPE }}/${{ env.PACKAGE_NAME }}`,
+              org: "FHIDev"
+            })
